config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "home#index"

  resources :lists, only: [ :show, :create, :destroy, :update ] do
    resources :items, only: [ :create, :destroy, :edit, :update ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
  belongs_to :user

  enum :priority, [ :minimal, :normal, :critical ]

  validates :title, presence: true

  default_scope -> { order(completed: :asc, priority: :desc) }
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :username ])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @lists = current_user.lists
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_list, only: %i[create edit update destroy]
  before_action :set_item, only: %i[edit update destroy]

  def create
    @item = @list.items.build(item_params)
    @item.user = current_user

    if @item.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to show_list_path(@list), notice: "Item was successfully created." }
      end
    else
      redirect_to list_path(@list)
    end
  end

  def edit
    @lists = current_user.lists
  end

  def update
    if @item.update(item_params)
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to list_path(@list), notice: "Item was successfully updated." }
      end
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to list_path(@list), notice: "Item was successfully destroyed." }
    end
  end

  private

  def set_list
    @list = current_user.lists.find(params[:list_id])
  end

  def set_item
    @item = @list.items.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :description, :priority, :date, :completed)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show destroy update]
  before_action :set_lists, only: %i[show]

  def show; end

  def update
    if @list.update(list_params)
      redirect_to @list, notice: "List updated successfully"
    else
      render :edit
    end
  end

  def create
    @list = current_user.lists.build(list_params)
    if @list.save
      redirect_to @list, notice: "List created successfully"
    else
      render :index
    end
  end

  def destroy
    @list.destroy
    redirect_to root_path, notice: "List deleted successfully"
  end

  private

  def set_list
    @list = current_user.lists.find(params[:id])
  end

  def set_lists
    @lists = current_user.lists
  end

  def list_params
    params.require(:list).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def item_border_color(item)
    case item.priority
    when "minimal"
      "border-green-400"
    when "normal"
      "border-yellow-400"
    when "critical"
      "border-red-900"
    end
  end

  def item_background_color(item)
    item.completed ? "border-none bg-base-300" : ""
  end

  def item_line_style(item)
     item.completed ? "line-through" : ""
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/index.html.erb
<% content_for :sidebar_content do %>
  <%= render 'lists/lists', lists: @lists %>
<% end %>

<% content_for :main_content do %>
  <div class="min-h-screen flex flex-col justify-start items-start p-6">
    <h1 class="text-4xl font-bold mb-4">Welcome, <%= current_user.username %>!</h1>
    <p class="text-lg mb-2">
      Here you can manage all your tasks efficiently. Use the side menu to create and view your lists.
    </p>
    <p class="text-lg mb-2">
      Stay organized and keep track of your daily activities with ease.
    </p>
  </div>
<% end %>

<%= render 'templates/sidebar_template' %>

app/views/items/_form.html.erb
<%= turbo_frame_tag "new_item_form" do %>
  <%= form_with(model: [list, list.items.build], local: false, html: { class: "space-y-4" }) do |form| %>
    <div class="form-control">
      <%= form.label :title, class: "label" %>
      <%= form.text_field :title, class: "input input-bordered", required: true %>
    </div>

    <div class="form-control">
      <%= form.label :description, class: "label" %>
      <%= form.text_area :description, class: "input input-bordered h-32" %>
    </div>  

    <div class="flex space-x-2">
      <div class="form-control w-1/2">
        <%= form.label :priority, class: "label" %>
        <%= form.select :priority, Item.priorities.keys.map { |priority| [priority.humanize, priority] }, {}, class: "select select-bordered w-full" %>
      </div>

      <div class="form-control w-1/2">
        <%= form.label :date, class: "label" %>
        <%= form.date_field :date, class: "input input-bordered" %>
      </div>
    </div>

    <div class="form-control mt-6">
      <%= form.submit "Add Item", class: "btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/items/_item.html.erb
<div id="item_<%= item.id %>" class='flex items-center justify-between p-4 bg-base-200 rounded-lg shadow-sm w-1/2 mb-2 border-l-8 <%= item_border_color(item) %> <%= item_background_color(item) %>'>
  <div class='<%= item_line_style(item) %>'>
    <h2 class="text-xl font-semibold"><%= item.title %></h2>
    <p class="text-gray-600"><%= truncate(item.description, length: 20) %></p>
  </div>
  <div>
    <div class="flex items-center space-x-4">
      <%= check_box_tag 'Completed', true, item.completed, class: 'checkbox checkbox-lg', method: :put, 
          data: { controller: 'checkbox', action: 'change->checkbox#update', checkbox_url_value: url_for([item.list, item])  } %>
     
     <%= render 'items/menu', item: item, list: item.list %>
    </div>
  </div>
</div>

app/views/items/_items.html.erb
<div id="items">
  <% list.items.each do |item| %>
    <%= render item %>
  <% end %>
</div>

app/views/items/_menu.html.erb
<div class="drawer drawer-end">
  <input id="my-drawer-<%= item.id %>" type="checkbox" class="drawer-toggle" />
  <div class="drawer-content">
    <!-- Page content here -->
    <label for="my-drawer-<%= item.id %>" class="drawer-button btn btn-sm btn-primary">
      <%= image_tag 'edit.svg' %>
    </label>
  </div>
  <div class="drawer-side">
    <label for="my-drawer-<%= item.id %>" aria-label="close sidebar" class="drawer-overlay"></label>
    <ul class="menu bg-base-200 text-base-content min-h-full w-1/3 p-4 space-y-4">
      <!-- Sidebar content here -->
      <li>
        <h2 class="text-2xl font-bold"><%= item.title %></h2>
        <p class="">
          <span><strong>Description:</strong> <br/> <%= item.description %><span>
        </p>
        <p class=""><strong>Priority:</strong> <%= item.priority.humanize %></p>
        <p class=""><strong>Date:</strong> <%= item.date.strftime('%d/%m/%Y') if item.date.present? %></p>
      </li>
      <li>
        <%= link_to 'Edit', edit_list_item_path(item.list, item, list: list), class: 'btn btn-sm btn-outline mr-2 mb-2 w-1/2' %>
        <%= link_to 'Delete' , list_item_path(item.list, item) , data: { turbo_confirm: 'Are you sure?', 
                                                                         turbo_method: :delete }, 
                                                                         class: 'btn btn-sm btn-error w-1/2' %>
      </li>
    </ul>
  </div>
</div>

app/views/items/create.turbo_stream.erb
<%= turbo_stream.replace 'items', partial: 'items/items', locals: { list: @list } %>

<%= turbo_stream.replace "new_item_form" do %>
  <%= render 'items/form', list: @list %>
<% end %>

app/views/items/destroy.turbo_stream.erb
<%= turbo_stream.replace 'items', partial: 'items/items', locals: { list: @list } %>

app/views/items/edit.html.erb
<% content_for :sidebar_content do %>
  <%= render 'lists/lists', lists: @lists %>
<% end %>


<% content_for :main_content do %>
  <%= form_with(model: [@list, @item], url: list_item_path(@list, @item, format: :html), local: true, class:'p-4 w-1/2') do |form| %>
    <div class="form-control mb-4">
      <%= form.label :title, class: "label font-bold" %>
      <%= form.text_field :title, class: "input input-bordered w-full", required: true %>
    </div>

    <div class="form-control mb-4">
      <%= form.label :description, class: "label font-bold" %>
      <%= form.text_area :description, class: "textarea textarea-bordered w-full h-32" %>
    </div>  
    
    <div class="flex space-x-4 mb-4">
      <div class="form-control w-1/2">
        <%= form.label :date, class: "label font-bold" %>
        <%= form.date_field :date, class: "input input-bordered w-full cursor-pointer" %>
      </div>

      <div class="form-control w-1/2">
        <%= form.label :priority, class: "label font-bold" %>
        <%= form.select :priority, Item.priorities.keys.map { |priority| [priority.humanize, priority] }, {}, class: "select select-bordered w-full" %>
      </div>
    </div>

    <div class="form-control mt-6">
      <%= form.submit "Add Item", class: "btn btn-primary w-full" %>
    </div>
  <% end %>
<% end %>

<%= render 'templates/sidebar_template'  %>

app/views/items/update.turbo_stream.erb
<%= turbo_stream.replace 'items', partial: 'items/items', locals: { list: @list } %>

app/views/layouts/_flash_msg.html.erb
<% flash.each do |type, msg|%>
  <% css_class = type == 'alert' ? 'error' : 'success' %>
  <div class="toast toast-top toast-center animate__animated animate__fadeIn animate__fadeOut animate__delay-2s z-50">
    <div class="alert alert-<%= css_class %>">
      <span><%= msg %></span>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Todo Final" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@latest/dist/full.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/flash_msg' if flash.present? %>
    <%= yield %>
  </body>
</html>
  

app/views/lists/_create_modal.html.erb
<dialog id="my_modal_2" class="modal">
  <div class="modal-box">
    <h3 class="text-lg font-bold">Create a new list</h3>
    <%= render 'lists/form', list: current_user.lists.build %>
  </div>
  <form method="dialog" class="modal-backdrop">
    <button>close</button>
  </form>
</dialog>

app/views/lists/_edit_modal.html.erb
<button class="btn btn-primary" onclick="my_modal_ed.showModal()">Edit List</button>
<dialog id="my_modal_ed" class="modal">
  <div class="modal-box">
    <h3 class="text-lg font-bold">Edit</h3>
    <%= render 'lists/form', list: list %>
  </div>
  <form method="dialog" class="modal-backdrop">
    <button>close</button>
  </form>
</dialog>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true, html: { class: "space-y-4" }) do |form| %>
  <div class="form-control">
    <%= form.label :title, class: "label" %>
    <%= form.text_field :title, autofocus: true, class: "input input-bordered", required: true %>
  </div>

  <div class="form-control mt-6">
    <%= form.submit class: "btn btn-primary w-full" %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div class="p-6 rounded-lg shadow-md relative">
  <h1 class="text-5xl font-bold mb-4"><%= list.title %></h1>
  <div class="absolute bottom-6 right-6 flex space-x-2">
    <%= render 'lists/edit_modal', list: list %>
    <%= button_to 'Delete List', list_path(list), method: :delete, 
                                                  data: { turbo_confirm: 'Are you sure you want to delete this list?' },
                                                  class: 'btn btn-error' %>
  </div>
</div>
<div class="p-6 space-y-4">

  <%= render 'items/items', list: list %>

  <button class="btn" onclick="my_modal_1.showModal()">
    <span class='mr-2'>Add new item</span>
    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
    </svg>
  </button>
  
  <dialog id="my_modal_1" class="modal">
    <div class="modal-box">
      <h3 class="text-lg font-bold">Create your item</h3>
      <p class="py-4">Press ESC key or click the button below to close</p>
      <%= render 'items/form', list: list %>
      <div class="modal-action">
        <form method="dialog">
          <button class="btn">Close</button>
        </form>
      </div>
    </div>
  </dialog>
</div>

app/views/lists/_list_modal.html.erb
<dialog id="my_modal_2" class="modal">
  <div class="modal-box">
    <h3 class="text-lg font-bold">Create a new list</h3>
    <%= render 'lists/form', list: current_user.lists.build %>
  </div>
  <form method="dialog" class="modal-backdrop">
    <button>close</button>
  </form>
</dialog>

app/views/lists/_lists.html.erb
<div class="flex flex-col space-y-1 mt-2">
  <p class='font-bold'>My lists</p>
    <% lists.each do |list| %>
      <%= link_to list.title, list_path(list), class: 'text-left w-full rounded 
                                                       hover:bg-base-100 text-md 
                                                       py-1 px-2' %>
    <% end %>
</div>

app/views/lists/show.html.erb
<%= content_for :sidebar_content do %>
  <%= render 'lists/lists', lists: @lists %>
<% end %>

<%= content_for :main_content do %>
  <%= render 'lists/list', list: @list %>
<% end %>

<%= render 'templates/sidebar_template' %>

app/views/profiles/profile.html.erb
<%= content_for :sidebar_content do %>
  <div class="flex flex-col space-y-1">
    <p class='font-bold'>My lists</p>
      <% @lists.each do |list| %>
        <%= link_to list.title, show_list_path(list), class: 'text-left w-full rounded hover:bg-base-100 text-md py-1 px-2' %>
      <% end %>
  </div>
<% end %>

<%= content_for :main_content do %>
  <%= render 'lists/list', list: @list if @list.present?%>
<% end %>


<%= render 'templates/sidebar_template' %>

app/views/templates/_sidebar_template.html.erb
<div class="drawer lg:drawer-open">
  <input id="my-drawer-cl" type="checkbox" class="drawer-toggle" />
  <div class="drawer-content flex flex-col">
    <label for="my-drawer-cl" class="btn btn-primary drawer-button lg:hidden">
      Open Menu
    </label>
    
    <!-- Page content here -->
     <%= yield :main_content %>
  </div>


  <div class="drawer-side">
    <label for="my-drawer-cl" aria-label="close sidebar" class="drawer-overlay"></label>
    <ul class="menu bg-base-200 text-base-content min-h-full w-80 p-4 flex flex-col justify-between">
      <!-- TOP -->
      <div>
        <a href="<%= root_path %>" class="text-2xl font-bold text-center mb-4 block">
          <%= current_user.username.capitalize %>'s Todo Space
        </a>

        <button class="btn btn-neutral flex items-center text-md mb-1 font-semibold hover:underline" onclick="my_modal_2.showModal()">
         <span class='mr-2'>Add new List</span>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
          </svg>
        </button>
        <%= yield :sidebar_content %>
      </div>
      <!-- TOP -->

      <!-- Bottom -->
      <div class="mt-auto flex flex-col justify-center w-full">
        <!-- Settings -->
        <div class="dropdown dropdown-top dropdown-end w-full">
          <div tabindex="0" role="button" class="btn btn-primary w-full">Settings</div>
          <ul tabindex="0" class="dropdown-content menu bg-base-100 rounded-box z-[1] w-full p-2 shadow">
            <li><%= link_to "Edit Account", edit_user_registration_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete } %></li>
          </ul>
        </div>
        <!-- Settings -->
      </div>
      <!-- Bottom -->

    </ul>
  </div>
</div>

<!-- Modal -->
<%= render 'lists/create_modal' %>